// Mocks generated by Mockito 5.4.6 from annotations
// in device_marketing_names/test/device_marketing_names_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:device_marketing_names/src/logic/base/device_info.dart' as _i4;
import 'package:device_marketing_names/src/logic/base/platform_info.dart'
    as _i3;
import 'package:device_marketing_names/src/models/device_info_data.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDeviceInfoData_0 extends _i1.SmartFake
    implements _i2.DeviceInfoData {
  _FakeDeviceInfoData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlatformInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatformInfo extends _i1.Mock implements _i3.PlatformInfo {
  MockPlatformInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isWeb => (super.noSuchMethod(
        Invocation.getter(#isWeb),
        returnValue: false,
      ) as bool);

  @override
  bool get isAndroid => (super.noSuchMethod(
        Invocation.getter(#isAndroid),
        returnValue: false,
      ) as bool);

  @override
  bool get isIOS => (super.noSuchMethod(
        Invocation.getter(#isIOS),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [DeviceInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceInfo extends _i1.Mock implements _i4.DeviceInfo {
  MockDeviceInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.DeviceInfoData> getInfo(_i3.PlatformInfo? platformInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInfo,
          [platformInfo],
        ),
        returnValue: _i5.Future<_i2.DeviceInfoData>.value(_FakeDeviceInfoData_0(
          this,
          Invocation.method(
            #getInfo,
            [platformInfo],
          ),
        )),
      ) as _i5.Future<_i2.DeviceInfoData>);
}
